/* Generated by the Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */

var framePtr = null;
var excHandler = 0;
var lastJSError = null;
if (typeof Int8Array === 'undefined') Int8Array = Array;
if (typeof Int16Array === 'undefined') Int16Array = Array;
if (typeof Int32Array === 'undefined') Int32Array = Array;
if (typeof Uint8Array === 'undefined') Uint8Array = Array;
if (typeof Uint16Array === 'undefined') Uint16Array = Array;
if (typeof Uint32Array === 'undefined') Uint32Array = Array;
if (typeof Float32Array === 'undefined') Float32Array = Array;
if (typeof Float64Array === 'undefined') Float64Array = Array;

function toJSStr(s_15403) {
		    var len = s_15403.length-1;
    var asciiPart = new Array(len);
    var fcc = String.fromCharCode;
    var nonAsciiPart = null;
    var nonAsciiOffset = 0;
    for (var i = 0; i < len; ++i) {
      if (nonAsciiPart !== null) {
        var offset = (i - nonAsciiOffset) * 2;
        var code = s_15403[i].toString(16);
        if (code.length == 1) {
          code = "0"+code;
        }
        nonAsciiPart[offset] = "%";
        nonAsciiPart[offset + 1] = code;
      }
      else if (s_15403[i] < 128)
        asciiPart[i] = fcc(s_15403[i]);
      else {
        asciiPart.length = i;
        nonAsciiOffset = i;
        nonAsciiPart = new Array((len - i) * 2);
        --i;
      }
    }
    asciiPart = asciiPart.join("");
    return (nonAsciiPart === null) ?
        asciiPart : asciiPart + decodeURIComponent(nonAsciiPart.join(""));
  

	
}

function makeNimstrLit(c_15003) {
		    var ln = c_15003.length;
    var result = new Array(ln + 1);
    var i = 0;
    for (; i < ln; ++i) {
      result[i] = c_15003.charCodeAt(i);
    }
    result[i] = 0; // terminating zero
    return result;
    

	
}
var nimvm_6539 = false;
var nim_program_result = 0;
var globalRaiseHook_12005 = [null];
var localRaiseHook_12010 = [null];
var outOfMemHook_12013 = [null];

function send_26021(msg_26023) {
	var F={procname:"webterminal.send",prev:framePtr,filename:"/home/johnd/Projects/webterminal/src/webterminal.nim",line:0};
	framePtr = F;
		F.line = 21;
		send(toJSStr(msg_26023));
	framePtr = F.prev;

	
}

function on_terminal_start_27001() {
	var F={procname:"app.on_terminal_start",prev:framePtr,filename:"app.nim",line:0};
	framePtr = F;
		F.line = 6;
		send_26021(makeNimstrLit("3\x0A2\x0A1\x0A"));
		F.line = 7;
		send_26021(makeNimstrLit("The repeating app has started."));
	framePtr = F.prev;

	
}
establish_terminal_on_start_function(on_terminal_start_27001);

function on_terminal_input_27009(msg_27011) {
	var F={procname:"app.on_terminal_input",prev:framePtr,filename:"app.nim",line:0};
	framePtr = F;
		F.line = 12;
		send_26021((makeNimstrLit("You just said \"").slice(0,-1)).concat(msg_27011.slice(0,-1),makeNimstrLit("\".")));
	framePtr = F.prev;

	
}
establish_terminal_on_input_function(on_terminal_input_27009);
